apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: node-exporter
  name: node-exporter
  namespace: monitor
spec:
  clusterIP: None
  ports:
  - name: scrape
    port: 9100
    protocol: TCP
  selector:
    app: node-exporter
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitor
spec:
  template:
    metadata:
      labels:
        app: node-exporter
      name: node-exporter
    spec:
      tolerations: 
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      hostNetwork: true
      hostPID: true
      hostIPC: true
      securityContext:
        runAsUser: 0
      containers:
      - image: alicfeng/node-gpu-exporter:1.0.0
        name: gpu
        volumeMounts:
          - mountPath: /etc/nvidia.prom
            name: nvidia
          - mountPath: /etc/disk.prom
            name: disk
          - mountPath: /etc/localtime
            name: localtime
      - image: prom/node-exporter:v1.0.1
        name: node-exporter
        volumeMounts:
          - mountPath: /run/systemd/private
            name: systemd-socket
            readOnly: true
          - mountPath: /etc/nvidia.prom
            name: nvidia
          - mountPath: /etc/disk.prom
            name: disk
          - mountPath: /etc/program.prom
            name: program
          - mountPath: /etc/localtime
            name: localtime
        env:
          - name: DIR
            value: "/etc"
        args:
          - "--collector.textfile.directory=$(DIR)"
          - "--no-collector.arp"
          - "--no-collector.bcache"
          - "--no-collector.bonding"
          - "--no-collector.conntrack"
          - "--no-collector.edac"
          - "--no-collector.entropy"
          - "--no-collector.filefd"
          - "--no-collector.diskstats"
          - "--no-collector.hwmon"
          - "--no-collector.infiniband"
          - "--no-collector.ipvs"
          - "--no-collector.netclass"
          - "--no-collector.netdev"
          - "--no-collector.netstat"
          - "--no-collector.nfs"
          - "--no-collector.nfsd"
          - "--no-collector.pressure"
          - "--no-collector.sockstat"
          - "--no-collector.time"
          - "--no-collector.timex"
          - "--no-collector.xfs"
          - "--no-collector.zfs"
        ports:
          - containerPort: 9100
            hostPort: 9100
            name: scrape
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9100
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 1
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /metrics
            port: 9100
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 2
      volumes:
        - hostPath:  
            path: /run/systemd/private
          name: systemd-socket
        - hostPath:  
            path: /etc/nvidia.prom
            type: FileOrCreate
          name: nvidia
        - hostPath:  
            path: /etc/disk.prom
            type: FileOrCreate
          name: disk
        - hostPath:  
            path: /etc/program.prom
            type: FileOrCreate
          name: program
        - hostPath:
            path: /etc/localtime
            type: File
          name: localtime
