version: '3'
services:
  postwoman:
    container_name: postwoman
    image: liyasthomas/postwoman
    ports:
      - ${POSTWOMAN_PORT:-8101}:3000
    restart: always

  excalidraw:
    container_name: excalidraw
    image: excalidraw/excalidraw
    ports:
      - ${EXCALIDRAW_PORT:-8101}:80
    restart: always

  callback_tool:
    container_name: callback_tool
    image: alicfeng/callback_tool:latest
    ports:
      - ${CALLBACK_TOOL_PORT:-8102}:80
    environment:
      ROUTE: "/api/demo/recv"
    restart: always

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    volumes:
      - ./srv/filebrowser/config.json:/filebrowser.json:ro
      - ${FILE_BROWSER_VOLUMN_DIR}:/srv/
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${FILE_BROWSER_HTTP_PORT:-8103}:80
    restart: always

  share:
    container_name: share
    image: alicfeng/share
    volumes:
      - ${SHARE_VOLUMN_DIR}:/www/files:ro
    ports:
      - ${SHARE_PORT:-8104}:80
    restart: always

  sonar:
    container_name: sonar
    image: sonarqube:community-beta
    ports:
      - ${SONAR_PORT:-8106}:9000
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: always

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

networks:
  default:
    external:
      name: ev-dev-network