apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-nginx-config
data:
  filebeat.yml: |-
    max_procs: 1
    scan_frequency: 5s
    encoding: utf-8
    ignore_older: 2h
    close_inactive: 5m
    harvester_buffer_size: 600000
    close_inactive: 5m
    close_timeout： 120m
    filebeat.prospectors:
      - type: log
        paths:
          - /var/log/nginx/access.log
        fields:
          app: www
          type: nginx-access
        fields_under_root: true
       - type: log
        paths:
          - /var/log/nginx/error.log
        fields:
          app: www
          type: nginx-error
        fields_under_root: true

    output.logstash:
      hosts: ['192.168.1.200:5044']

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: elk-nginx
spec:
  template:
    metadata:
      labels:
        project: k8s
        app: filebeat
    spec:
      containers:
        - name: elk-nginx
          image: hub-mirror.c.163.com/nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 6
            timeoutSeconds: 20
          volumeMounts:
            - name: nginx-logs
              mountPath: /var/log/nginx/

        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.7.1
          args: ["-c", "/etc/filebeat.yml","-e"]
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: filebeat-config
              mountPath: /etc/filebeat.yml
              subPath: filebeat.yml
            - name: nginx-logs
              mountPath: /var/log/nginx/

      volumes:
        - name: nginx-logs
          emptyDir: {}
        - name: filebeat-config
          configMap:
            name: filebeat-nginx-config
