kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: monitor
  labels:
    app: prometheus
    component: core
  annotations:
    prometheus.io/scrape: 'true'
    external-dns.alpha.kubernetes.io/hostname: prometheus.quicknuke.com.
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      name: query-api
  selector:
    app: prometheus
    component: core

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: prometheus-core
  namespace: monitor
  labels:
    app: prometheus
    component: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus-main
      labels:
        app: prometheus
        component: core
    spec:
      nodeSelector:
        kubernetes.io/hostname: master
      containers:
        - name: prometheus
          image: prom/prometheus:v2.23.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--web.enable-lifecycle"
            - "--storage.tsdb.retention=7d"
          ports:
            - containerPort: 9090
              name: evmonitor
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: prometheus-config-volume
              mountPath: /etc/prometheus
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        - name: prometheus-storage-volume
          emptyDir: {}
        - hostPath:  
            path: /etc/localtime
          name: localtime
